# Detection capability

In [1]:
import numpy as np

def messageBit(k):

    message=[]

    for i in range(2**k):

        for x in list(np.binary_repr(i,k)):

            message.append((x))

    message=np.array(message).reshape((-1,k)).astype(int)

    return message

#This function messageBit(k) takes an integer k as input, generates all possible messages of length k (2^k in total),
#and converts each message into a binary array. It then returns the binary array of messages as a numpy array.



def generateCodeword(message,parity):

    I=np.identity(message.shape[1])

    G=np.concatenate((parity,I),axis=1).astype(int)
    print("Its (%d,%d) codeword"%(I.shape[1]+I.shape[0]-1,I.shape[0]))

    codeWords=np.matmul(message,G)%2
    print("codeWords",codeWords)

    return codeWords
#This function generateCodeword(message, parity) takes two arguments: the message as a numpy array and a parity matrix
#as a numpy array. It generates a generator matrix G by concatenating the parity matrix and an identity matrix of size same
#as the number of columns in the message matrix. It then multiplies the message matrix with the generator matrix G 
#and applies modulo 2 to each element of the resulting matrix to generate codewords. Finally, it prints the dimensions
#of the generated codewords and returns them as a numpy array.
 

def DetectionAndCorrectionCapability(codeWords):

    weights=codeWords.sum(axis=1)
    print("weigths",weights)
    dmin=weights[weights>0].min()

    correctionCapability=(dmin-1)/2

    detectionCapability=dmin-1

    print("The Linear Block Code is capable of detecting %d bit or fewer number of error."%(detectionCapability))

    print("The Linear Block Code is capable of correcting %d bit or fewer number of error"%(correctionCapability))

#This function DetectionAndCorrectionCapability(codeWords) takes a numpy array of codewords as input. It calculates the weight
#(number of non-zero elements) of each codeword and finds the minimum non-zero weight dmin. It then calculates the 
#capabilities of the linear block code for error detection and error correction. Finally, it prints the capabilities of the code.

 

k=int(input("Enter the number of bits for message: "))

parity=np.array(input("Enter the parity bits rowise: ").split()).reshape((k,-1)).astype(int)

codeWords=generateCodeword(messageBit(k),parity)

DetectionAndCorrectionCapability(codeWords)
#This code takes user input for the number of bits in the message (k) and the parity matrix (parity). It then generates 
#the message matrix using the messageBit(k) function and generates the codewords using the generateCodeword(message, parity)
#function. Finally, it calculates the capabilities of the code using the DetectionAndCorrectionCapability(codeWords) function 
#and prints the results.

 

Enter the number of bits for message: 3
Enter the parity bits rowise: 1 0 1
Its (5,3) codeword
codeWords [[0 0 0 0]
 [1 0 0 1]
 [0 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [0 1 0 1]
 [1 1 1 0]
 [0 1 1 1]]
weigths [0 2 1 3 2 2 3 3]
The Linear Block Code is capable of detecting 0 bit or fewer number of error.
The Linear Block Code is capable of correcting 0 bit or fewer number of error


# railfence cipher

In [2]:
import numpy as np

def encrypt(secret, depth):
    msg = np.array(list(secret))
    print(msg)
    if len(msg) % depth != 0:
        msg = np.append(msg, ['X'] * (depth - (len(msg) % depth)))
    print(msg)
    msg = msg.reshape((depth, -1), order='F')
    print(msg)
    return "".join(msg.flatten())
#The encrypt(secret, depth) function takes two arguments - a string secret and an integer depth. The function first converts
#the string into a NumPy array, msg, and then checks if the length of msg is divisible by depth. If not, it appends 
#depth - (len(msg) % depth) number of 'X' characters to msg. The msg array is then reshaped into a 2-dimensional array 
#with depth number of rows, and as many columns as needed. Finally, the flattened version of the reshaped array is 
#returned as a string.

def decrypt(secret, depth):
    msg = np.array(list(secret))
    msg = msg.reshape((-1, depth), order='F')

    return "".join(msg.flatten())
#The decrypt(secret, depth) function takes two arguments - a string secret and an integer depth. The function first converts
#the string into a NumPy array, msg, and then reshapes it into a 2-dimensional array with -1 number of rows and depth number
#of columns. The flattened version of the reshaped array is then returned as a string.

secret = str(input("Enter the secret to encrypt: ")).replace(" ", "").upper()

depth = int(input("Enter the depth: "))

encrypted = encrypt(secret, depth)
decrypted = decrypt(encrypted, depth)

print("Encrypted:", encrypted)
print("Decrypted:", decrypted)

Enter the secret to encrypt: Hello World
Enter the depth: 2
['H' 'E' 'L' 'L' 'O' 'W' 'O' 'R' 'L' 'D']
['H' 'E' 'L' 'L' 'O' 'W' 'O' 'R' 'L' 'D']
[['H' 'L' 'O' 'O' 'L']
 ['E' 'L' 'W' 'R' 'D']]
Encrypted: HLOOLELWRD
Decrypted: HELLOWORLD


# Vernum cipher

In [ ]:
import numpy as np;

key = str(input("Enter the key: ")).replace(" ", "").upper()
#This line prompts the user to enter a key to use for encryption and decryption, removes any spaces from the input, 
#and converts it to uppercase.

def encrypt(secret):
    msg = list(secret.replace(" ", "").upper())
    keys = key * (len(msg) // len(key) + 1)
    # This line generates a repeated string of the key input that is long enough to match the length of the msg input.

    print(msg)
    print(keys)
    crypted = []
    #This line initializes an empty list to store the encrypted characters.

    for i in range(0, len(msg)):
    # This line starts a loop that iterates over each character in the msg input.
        x = ord(msg[i]) - 65 #This line converts the ASCII value of the current character to a zero-based index.
        y = ord(keys[i]) - 65 #This line converts the ASCII value of the corresponding character in the keys input to a zero-based index.

        crypted.append(chr(((x + y) % 26) + 65))
        #This line performs the encryption by adding the two indexes together, taking the result modulo 26, and 
        #converting the result back to an ASCII character.
    return "".join(crypted) #This line returns the encrypted message as a single string.

def decrypt(secret):
    msg = list(secret.replace(" ", "").upper())
    keys = key * (len(msg) // len(key) + 1)

    print(msg)
    print(keys)

    crypted = []

    for i in range(0, len(msg)):
        x = ord(msg[i]) - 65
        y = ord(keys[i]) - 65

        crypted.append(chr(((x ^ y) % 26) + 65))
        #This line performs the decryption by XORing the two indexes together, taking the result modulo 26, and converting
        #the result back to an ASCII character.
    return "".join(crypted)

while True:
    secret = str(input("Enter the secret: "))

    encrypted = encrypt(secret)
    decrypted = decrypt(encrypted)

    print("Encrypted: ", encrypted)
    print("Decrypted: ", decrypted)
    
if input("Continue? (y/n)") == 'n':
    break

# Linear Block

In [ ]:
import numpy as np

n = int(input("Enter the number of code bits: "))
# takes user input to determine the total number of bits in the code, including both the message bits and the parity bits.
k = int(input("Enter the number of message bits: "))

parity = np.array(list(map(int, input("Enter the parity bits: ").strip().split()))).reshape((k, n-k))
#takes user input for the parity bits, creates an array from the input values, and reshapes the array to have dimensions (k, n-k).

gen = np.append(np.identity(k, dtype=int), parity, axis=1)
# constructs the generator matrix for the code using the identity matrix and the parity bits.
print(gen)

def encode(msg):
    sent = np.array(list(map(int, msg.zfill(n-k))))
    code = np.matmul(sent, gen) % 2
    return "".join(map(str, code))
# takes the message as input and returns the encoded message using the generator matrix. It first converts the message to a 
#numpy array of size (n-k) and then multiplies it with the generator matrix using np.matmul. The resulting code is returned 
#as a string.


def decode(msg):
    sent = np.array(list(map(int, msg)))

    rcvd = sent.copy()
    
    if np.random.randint(0, 2):
        # corrupt a random bit
        pos = np.random.randint(0, len(rcvd))
        print("Corrupting bit at position", pos)
        rcvd[pos] = (rcvd[pos] + 1) % 2
    
    print("Received: ", "".join(map(str, rcvd)))
    
    H = np.append(parity.T, np.identity(n - k, dtype=int), axis=1)
    syndrome = np.matmul(rcvd, H.T) % 2
    
    if np.all(syndrome == 0):
        print("No error")
    else:
        pos = np.where(np.all(H.T == syndrome, axis=1))[0][0]
        print("Error at position", pos)
        rcvd[pos] = (rcvd[pos] + 1) % 2

    return "".join(map(str, rcvd))
# takes the received code as input and returns the decoded message using Hamming code. It first finds the syndrome by 
#multiplying the received code with the parity matrix. If the syndrome is all zeros, then there is no error and the received
#code is returned as is. Otherwise, the position of the error is determined by finding the row of the parity matrix that 
#matches the syndrome. The bit at that position in the received code is flipped and the corrected code is returned as a string.
msg = input("Enter the message: ")

encoded = encode(msg)
print("Encoded: ", encoded)

decoded = decode(encoded)
print("Decoded: ", decoded)

original_msg = decoded[:k]
print("Original message: ", original_msg)

# Playfair Cipher

In [ ]:
import numpy as np;

letters = [chr(i) for i in range(65, ord('I'))] + [chr(i) for i in range(ord('J')+1, 91)]

key = str(input("Enter the key: ")).replace(" ", "").upper()

if 'I' not in key and 'J' not in key:
    key += 'I'

key = list(dict.fromkeys(list(key) + letters))

print(np.array(key).reshape(-1, 5))
#The code first generates a list of letters (uppercase) from A to H and I to Z, excluding J. Then it prompts the user to enter
#a key, which is converted to uppercase and all spaces are removed. If the key does not contain 'I' or 'J', it is appended
#with 'I'. The list of letters generated earlier is combined with the key, duplicates are removed, and the resulting list is
#assigned to the variable 'key'. This key is reshaped into a 5x5 array using NumPy's reshape function and printed.

def encrypt(secret):
    msg = list(secret.replace(" ", "").upper())
    crypted = []

    if len(msg) % 2:
        msg.append('X')
    
    for i in range(0, len(msg), 2):
        if msg[i] == 'J':
            msg[i] = 'I'
        if msg[i+1] == 'J':
            msg[i+1] = 'I'
        
        a = key.index(msg[i])
        b = key.index(msg[i+1])

        rowA, rowB = a // 5, b // 5
        colA, colB = a % 5, b % 5

        if rowA == rowB:
            crypted.append(key[(a+1) % 5 + rowA * 5])
            crypted.append(key[(b+1) % 5 + rowB * 5])
        elif colA == colB:
            crypted.append(key[(a+5) % 25])
            crypted.append(key[(b+5) % 25])
        else:
            crypted.append(key[rowA * 5 + colB % 5])
            crypted.append(key[rowB * 5 + colA % 5])
    
    return "".join(crypted)
#The 'encrypt' function takes a message, removes spaces and converts it to uppercase. If the length of the message is odd, 
#it appends an 'X' to make it even. The function then iterates over the message in pairs, replacing 'J' with 'I'. It then
#finds the indices of each letter in the key, determines their positions on the 5x5 grid, and applies the Playfair encryption
#rules to each pair of letters. The encrypted letters are added to a list called 'crypted' and joined to form a string, 
#which is returned.

def decrypt(secret):
    msg = list(secret.replace(" ", "").upper())
    decrypted = []

    for i in range(0, len(msg), 2):
        a = key.index(msg[i])
        b = key.index(msg[i+1])

        rowA, rowB = a // 5, b // 5
        colA, colB = a % 5, b % 5

        if rowA == rowB:
            decrypted.append(key[(a-1) % 5 + rowA * 5])
            decrypted.append(key[(b-1) % 5 + rowB * 5])
        elif colA == colB:
            decrypted.append(key[(a-5) % 25])
            decrypted.append(key[(b-5) % 25])
        else:
            decrypted.append(key[rowA * 5 + colB % 5])
            decrypted.append(key[rowB * 5 + colA % 5])
    
    return "".join(decrypted)
#The 'decrypt' function takes an encrypted message, removes spaces and converts it to uppercase. It then iterates over the
#message in pairs, finds the indices of each letter in the key, determines their positions on the 5x5 grid, and applies the
#Playfair decryption rules to each pair of letters. The decrypted letters are added to a list called 'decrypted' and joined
#to form a string, which is returned.

while True:
    secret = str(input("Enter the secret: ")).replace(" ", "").upper()

    for i in range(65, 65+26):
        double = chr(i) * 2
        fixed = chr(i) + 'X' + chr(i) 
        secret = secret.replace(double, fixed)

    encrypted = encrypt(secret)
    decrypted = decrypt(encrypted)

    print("Encrypted: ", encrypted)
    print("Decrypted: ", decrypted)

    if input("Continue? (y/n)") == 'n':
        break
    #The code then enters a loop that repeatedly prompts the user to enter a message and applies the 'encrypt' and 'decrypt'
    #functions to it. If the message contains any double letters (e.g., "LL"), they are replaced with a letter 'X' between them
    #(e.g., "LX"). The encrypted and decrypted messages are printed, and the loop continues until the user chooses to stop.

# Hill Cipher

In [ ]:
import numpy as np

multi_inv = {
    1: 1,
    3: 9,
    5: 21,
    7: 15,
    9: 3,
    11: 19,
    15: 7,
    17: 23,
    19: 11,
    21: 5,
    23: 17,
    25: 25
}
#This is a dictionary containing multiplicative inverses of some numbers modulo 26. It is used in the decryption function
#to calculate the inverse of the key matrix.

def encrypt(secret, key):
    msg = np.array([ord(x) - 65 for x in secret])

    encrypted = ""

    if len(msg) % len(key) != 0:
        msg = np.append(msg, [23] * (len(key) - (len(msg) % len(key))))
    
    msg = msg.reshape((-1, len(key)))
    key = np.array(key)

    for triplet in msg:
        multed = np.matmul(triplet, key) % 26
        encrypted += "".join([chr(x + 65) for x in multed])

    return encrypted
#This function takes two arguments, secret and key. The secret argument is a string of characters to be encrypted. The key
#argument is a square matrix of integers, used as the encryption key. The function first converts each character in the secret
#string to its corresponding ASCII code and subtracts 65 (the ASCII code of 'A') from it to obtain a sequence of integers. 
#It then pads this sequence with the integer 23 (which corresponds to 'X') to make its length a multiple of the size of the key
#matrix. The padded sequence is then reshaped into a 2D array and multiplied by the key matrix using NumPy's matmul function.
#The result is then reduced modulo 26 and converted back to a string of characters. This string is the encrypted message.

def decrypt(secret, key):
    msg = np.array([ord(x) - 65 for x in secret])

    decrypted = ""
    
    msg = msg.reshape((-1, len(key)))
    det = int(np.linalg.det(key))

    inv = np.round_(det * np.linalg.inv(key) * multi_inv[det % 26]).astype(int) % 26

    for triplet in msg:
        multed = np.matmul(triplet, inv) % 26
        decrypted += "".join([chr(x + 65) for x in multed])

    return decrypted
#This function takes two arguments, secret and key. The secret argument is the encrypted message, as a string of characters.
#The key argument is the same square matrix of integers used to encrypt the message. The function first converts each character
#in the secret string to its corresponding ASCII code and subtracts 65 (the ASCII code of 'A') from it to obtain a sequence of
#integers. This sequence is then reshaped into a 2D array and multiplied by the inverse of the key matrix, using NumPy's matmul
#function. The inverse of the key matrix is calculated using NumPy's linalg.inv function, and the multiplicative inverse of its
#determinant (mod 26) is used as a coefficient, based on the multi_inv dictionary. The resulting sequence of integers is reduced
#modulo 26 and converted back to a string of characters. This string is the decrypted message.

secret = str(input("Enter the secret to encrypt: ")).replace(" ", "").upper()

dims = int(input("Enter the dimensions of the key: "))

key = np.array(list(map(int, input("Enter the key: ").strip().split(" ")))).reshape((dims, dims))

encrypted = encrypt(secret, key)

victim = str(input("Enter the secret to decrypt: ")).replace(" ", "").upper()

decrypted = decrypt(victim, key)

print("Encrypted: ", encrypted)
print("Decrypted: ", decrypted)

# Monoalphabetic Cipher

In [ ]:
import numpy as np

letters = [chr(x + 65) for x in range(26)]

print("".join(letters))

np.random.shuffle(letters)
#The first part of the code creates a list of capital letters from A to Z and prints them out, then shuffles the list and
#prints it again. This is not directly related to the encryption and decryption functions, but it is useful for generating 
#a random substitution cipher.

print("".join(letters))
def encrypt(secret):
    encrypted = []

    for letter in secret:
        if letter.isalpha():
            encrypted.append(letters[ord(letter) - 97])
        else:
            encrypted.append(letter)

    return "".join(encrypted)
#The encrypt function takes a string secret as input and returns a string with each letter replaced by a randomly chosen letter
#from the shuffled list of letters. If the input character is not a letter, it is kept as is.

def decrypt(secret):
    decrypted = []

    for letter in secret:
        if letter.isalpha():
            decrypted.append(chr(letters.index(letter) + 97))
        else:
            decrypted.append(letter)

    return "".join(decrypted)
#The decrypt function takes an encrypted string and returns the original string by looking up the index of each letter in the
#shuffled list of letters and converting it back to its original letter.

secret = str(input("Enter the secret: "))

encrypted = encrypt(secret)
decrypted = decrypt(encrypted)

print("Encrypted:", encrypted)
print("Decrypted:", decrypted)

# Columnar cipher

In [ ]:
import numpy as np

def encrypt(secret, depth, key):
    msg = np.array(list(secret))

    encrypted = ""
    
    if len(msg) % depth != 0:
        msg = np.append(msg, ['X'] * (depth - len(msg) % depth))
    
    msg = msg.reshape((depth, -1))[:, np.argsort(key)].T

    for group in msg:
        encrypted += "".join(group)
    
    return encrypted
#The encrypt function takes three arguments: secret, a string to be encrypted; depth, an integer indicating the length of
#each group of characters to be encrypted together; and key, a list of integers indicating the order in which to group the 
#characters. The function first converts the input string to a NumPy array and pads it with "X" characters if necessary to 
#ensure that the length of the array is divisible by the depth. It then reshapes the array into a 2D array with depth rows and
#an appropriate number of columns, and reorders the columns based on the key list. Finally, the function concatenates the 
#characters in each row and returns the encrypted string.

def decrypt(secret, depth, key):
    msg = np.array(list(secret))

    decrypted = ""
    
    msg = msg.reshape((-1, depth)).T

    msg = msg[:, key]

    for group in msg:
        decrypted += "".join(group)
    
    return decrypted
#The decrypt function takes the same three arguments as encrypt, and it reverses the encryption process. It first converts the
#string into a NumPy array of characters, then reshapes the array to have depth columns and as many rows as needed. The columns
#are reordered using the key list and the resulting array is transposed so that the characters are grouped together by row.
#Finally, it concatenates the characters into a string and returns it.
secret = str(input("Enter the secret: ")).replace(" ", "").upper()

depth = int(input("Enter the depth: "))

key = list(map(int, input("Enter the key: ").strip().split()))

if key == []:
    key = np.arange(len(secret) // depth + 1)

encrypted = encrypt(secret, depth, key)
double_encrypted = encrypt(encrypted, depth, key)

decrypted = decrypt(encrypted, depth, key)
double_decrypted = decrypt(decrypt(double_encrypted, depth, key), depth, key)

print("Encrypted: ", encrypted)
print("Double Encrypted: ", double_encrypted)

print("Decrypted: ", decrypted)
print("Double Decrypted: ", double_decrypted)
#The main part of the code prompts the user to enter a secret string, a depth value, and a key list. If no key is entered,
#it generates a default key based on the length of the secret string and the depth value. It then calls the encrypt function
#to encrypt the secret string using the given depth and key, and stores the result in the encrypted variable. It then calls the
#encrypt function again with the encrypted string as input to double-encrypt it. The decrypt function is then called twice,
#once with the encrypted string as input and once with the double_encrypted string as input, to decrypt both strings. 
#The decrypted strings are then printed out for comparison.

In [ ]:
#Multiple inverse

In [ ]:
def multi_inv(num, base):
#The function takes two arguments: num is the number for which we want to find the multiplicative inverse, and base is the base
#in which we are working.
    for i in range(1, base):
        if (num * i) % base == 1:
            return i
    
    return -1

#Here is how the function works:

#It loops through all integers from 1 to base - 1 (excluding base itself), checking whether the product of num and the current
#integer is congruent to 1 modulo base.
#If it finds an integer that satisfies the condition, it returns that integer as the multiplicative inverse of num in the
#given base.
#If it finishes looping through all integers without finding a suitable inverse, it returns -1 to indicate that the inverse 
#does not exist.
num = int(input("Enter the number: "))
base = int(input("Enter the base: "))

inv = multi_inv(num, base)

if inv == -1:
    print("Multiplicative inverse for", num, "in base", base, "does not exist.")
else:
    print("Multiplicative inverse:", inv)

# Caesar Cipher

In [ ]:
def encrypt(secret, key):
    encrypted = []

    for letter in secret:
        if letter.isalpha():
            encrypted.append(chr(((ord(letter) - 97 + key) % 26) + 65))
        else:
            encrypted.append(letter)

    return "".join(encrypted)

def decrypt(secret, key):
    decrypted = []

    for letter in secret:
        if letter.isalpha():
            decrypted.append(chr(((ord(letter) - 65 - key) % 26) + 97))
        else:
            decrypted.append(letter)

    return "".join(decrypted)

secret = str(input("Enter the secret: "))

key = int(input("Enter the key: "))

encrypted = encrypt(secret, key)
decrypted = decrypt(encrypted, key)

print("Encrypted:", encrypted)
print("Decrypted:", decrypted)